.\" -*- nroff -*-
.TH ARPING 8 "January 1999" "iputils-ss990107" "Linux Programmer's Manual"
.SH NAME
arping \- Ping <address> on device <interface> by ARP packets,
using source address <source>.
.SH SYNOPSIS
.B arping
[
.B \-D
]
[
.B \-U
]
[
.B \-A
]
[
.B \-c
count
]
[
.B \-w
timeout
]
[
.B \-q
]
[
.B \-s
source
]
.B \-I
interface
address
.SH DESCRIPTION
Ping <address> on device <interface> by ARP packets,
using source address <source>.
.SH OPTIONS
.TP
.I -c count
number of pings.
.TP
.I -w timeout
stop after this time.
.TP
.I -q
do not print any messages.
.TP
.I -D
duplicate address detection mode.
Returns 0, if DAD suceeded i.e. no replies
are received.
.TP
.I -U
Unsolicited ARP mode to update neighbours' ARP caches.
.TP
.I -A
The same as -U
, but ARP REPLY packets used instead
of ARP REQUEST.
.TP
If -s option is absent, source address is:
1. In normal mode calculated from routing tables.
2. In DAD (-D) mode set to 0.0.0.0
3. In Unsilicited ARP mode (-U,-A) set to <address>
.SH WARNING
GENERAL NOTE: all these applets, except for tracepath[6]
should be excecutabel only with CAP_NET_RAWIO capability.
To all that I know, they are safe to be used as setuid root.
.SH AUTHOR
.B arping
was written by Alexey Kuznetsov <kuznet@ms2.inr.ac.ru>
.SH BUGS
If someone will dig out bugs, which
were fixed after my versions were cloned: PLEASE, tell me!
.SH AVAILABILITY
.B arping
is part of the iputils-ss990107 package and is available for anonymous 
ftp <ftp://ftp.inr.ac.ru/ip-routing/iputils-ss990107.tar.gz>
.SH SEE ALSO
.BR ping (8),
.BR clockdiff (8),
.BR tracepath (8)
