.Id $Id: clockdiff.8.in,v ss990107 1999/01/07 15:59:58 ig25 Exp $
.TH CLOCKDIFF 8 "Jan 1999" local "Iputils-ss990107"
.SH NAME
clockdiff \- Measures clock difference between us and <destination> with 1msec
resolution. Without -o option it uses icmp timestamps, with -o
it uses icmp echo with timestamp IP option.
.SH SYNOPSIS
.B clockdiff
.RB [ -o | -o1 ]
<destination>
.SH WARNINGS
.TP
* some nodes (f.e. Solaris<2.4) do not support icmp
timestamps. clockdiff -o still works.
.TP
* some nodes (Cisco) use non-standard timestamps,
which makes clockdiff useless.
.TP
* some nodes use wrong timestamps (Solaris>2.4), if
run xntpd. Seems, it uses different clock source,
which is synchronized to time-of-day clock periodically.
.TP
* -o1 uses three-node tstamp. What option (-o or -o1)
works better depends on target host.

