.\" -*- nroff -*-
.TH TRACEPATH6 8 "April 2001" "iputils-20001110" "System Manager's Manual"
.SH NAME
tracepath6 \- traces path taken by IPv6 packets to <destination> 
discovering MTU along this path
.SH SYNOPSIS
.B tracepath6
[-b] [-n] destination [ port ]
.SH OPTIONS
.TP
.B \-n
Do not attempt to resolve DNS records for routers or hosts traversed.
.TP
.B \-b
Show both the hostname and the IPv6 address of each hop.
.SH DESCRIPTION
It traces path to <destination> discovering MTU along this path.
It uses UDP port <port> or some random port.
tracepath6 is good replacement for traceroute6
and classic example of application Linux error queues.
tracepath is worse, because commercial IP routers
do not return enough information in icmp error messages.
Probably, it will change, when they will be updated.
For now it uses Van Jacobson's trick, sweaping a range
of UDP ports to maintain trace history.
using source address <source>.
.SH AUTHOR
.B tracepath6
was written by Alexey Kuznetsov <kuznet@ms2.inr.ac.ru>
.SH BUGS
Please use the Debian bug tracking system (see http://bugs.debian.org)
when reporting bugs.  They will be forwarded upstream if necessary.
.SH AVAILABILITY
.B tracepath6
is part of the iputils-20001110 package and is available for anonymous 
ftp <ftp://ftp.inr.ac.ru/ip-routing/iputils-ss001110.tar.gz>
.SH SEE ALSO
.BR ping (8),
.BR tracepath (8),
.BR traceroute6 (8)
